'use client';
// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
import { useEffect, useState } from 'react';
import { onAuthStateChanged, User } from 'firebase/auth';

import { useAuth } from '../provider';

/**
 * A hook that returns the currently signed-in user.
 *
 * This hook is a wrapper around the onAuthStateChanged method from the
 * Firebase Auth SDK.
 *
 * @returns The currently signed-in user, or null if there is no user.
 */
export function useUser() {
  const auth = useAuth();
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      setUser(user);
      setLoading(false);
    });

    return () => unsubscribe();
  }, [auth]);

  return { user, loading };
}
